[package]
name = "github-deployment"
version = "0.1.0"
authors = ["Sergey Fedorov <oni.strech@gmail.com>"]

[dependencies]
serde = "1.0.9"
serde_json = "1.0.2"
curl = "0.4.8"
clap = "2.26.0"
lazy_static = "0.2.8"
